#pragma once

#pragma region OPCODES
#define OPCODE_LIST \
    abort,      \
    incr,       \
    decr,       \
    negr,       \
    pushr,      \
    popr,       \
    movri,      \
    movrr,      \
    addri,      \
    addrr,      \
    subri,      \
    subrr,      \
    mulri,      \
    mulrr,      \
    divri,      \
    divrr,      \
    sdivri,     \
    sdivrr,     \
    modri,      \
    modrr,      \
    smodri,     \
    smodrr,     \
    andri,      \
    andrr,      \
    orri,       \
    orrr,       \
    xorri,      \
    xorrr,      \
    lslri,      \
    lslrr,      \
    lsrri,      \
    lsrrr,      \
    asrri,      \
    asrrr,      \
    movneri,    \
    movnerr,    \
    moveqri,    \
    moveqrr,    \
    movgeri,    \
    movgerr,    \
    movgtri,    \
    movgtrr,    \
    movleri,    \
    movlerr,    \
    movltri,    \
    movltrr,    \
    movhsri,    \
    movhsrr,    \
    movhiri,    \
    movhirr,    \
    movlsri,    \
    movlsrr,    \
    movlori,    \
    movlorr,    \
    outri,      \
    outrr,      \
    inri,       \
    inrr,       \
    ldsbrr,     \
    ldsbrir,    \
    ldshrr,     \
    ldshrir,    \
    ldubrr,     \
    ldubrir,    \
    lduhrr,     \
    lduhrir,    \
    ldwrr,      \
    ldwrir,     \
    stbir,      \
    stbiir,     \
    stbrr,      \
    stbrir,     \
    sthir,      \
    sthiir,     \
    sthrr,      \
    sthrir,     \
    stwir,      \
    stwiir,     \
    stwrr,      \
    stwrir,     \
    learl,      \
    learil,     \
    cmpii,      \
    cmpir,      \
    cmpri,      \
    cmprr,      \
    b,          \
    bl,         \
    bne,        \
    beq,        \
    bge,        \
    bgt,        \
    ble,        \
    blt,        \
    bhs,        \
    bhi,        \
    bls,        \
    blo,        \
    br,         \
    ret,        \
    msg,        \
    halt,
#pragma endregion

#pragma region MNEMONICS
#define MNEMONICS_LIST \
    inc,    \
    dec,    \
    neg,    \
    push,   \
    pop,    \
    ret,    \
    halt,   \
    mov,    \
    add,    \
    sub,    \
    mul,    \
    div,    \
    sdiv,   \
    mod,    \
    smod,   \
    and,    \
    or,     \
    xor,    \
    lsl,    \
    lsr,    \
    asr,    \
    movne,  \
    moveq,  \
    movge,  \
    movgt,  \
    movle,  \
    movlt,  \
    movhs,  \
    movhi,  \
    movls,  \
    movlo,  \
    out,    \
    in,     \
    ldsb,   \
    ldsh,   \
    ldub,   \
    lduh,   \
    ldw,    \
    stb,    \
    sth,    \
    stw,    \
    lea,    \
    cmp,    \
    b,      \
    bl,     \
    bne,    \
    beq,    \
    bge,    \
    bgt,    \
    ble,    \
    blt,    \
    bhs,    \
    bhi,    \
    bls,    \
    blo,    \
    br,     \
    msg,
#pragma endregion

#pragma region REGS
#define REGISTER_LIST \
    r0,     \
    r1,     \
    r2,     \
    r3,     \
    r4,     \
    r5,     \
    r6,     \
    r7,     \
    r8,     \
    r9,     \
    r10,    \
    r11,    \
    r12,    \
    r13,    \
    r14,    \
    r15,    \
    r16,    \
    r17,    \
    r18,    \
    r19,    \
    r20,    \
    r21,    \
    r22,    \
    r23,    \
    r24,    \
    r25,    \
    r26,    \
    r27,    \
    r28,    \
    r29,    \
    r30,    \
    r31,    \
    pc,     \
    lr,     \
    fp,     \
    sp,     \
    cc,     \
    cyc
#pragma endregion

#pragma region ASM DIRECTIVES
#define DIRECTIVE_LIST \
    text,   \
    data,   \
    byte,   \
    hword,  \
    word,   \
    zero,   \
    ascii,  \
    align
#pragma endregion
